/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardTouristRouteImport } from './routes/dashboard/tourist'
import { Route as DashboardDriverRouteImport } from './routes/dashboard/driver'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as Auth_layoutRouteImport } from './routes/auth/__layout'
import { Route as DashboardTouristIndexRouteImport } from './routes/dashboard/tourist/index'
import { Route as DashboardDriverIndexRouteImport } from './routes/dashboard/driver/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardTouristTripsRouteImport } from './routes/dashboard/tourist/trips'
import { Route as DashboardTouristReceiptsRouteImport } from './routes/dashboard/tourist/receipts'
import { Route as DashboardTouristMessagesRouteImport } from './routes/dashboard/tourist/messages'
import { Route as DashboardTouristItinerariesRouteImport } from './routes/dashboard/tourist/itineraries'
import { Route as DashboardTouristBidsRouteImport } from './routes/dashboard/tourist/bids'
import { Route as DashboardDriverVerificationRouteImport } from './routes/dashboard/driver/verification'
import { Route as DashboardDriverVehicleRouteImport } from './routes/dashboard/driver/vehicle'
import { Route as DashboardDriverTripsRouteImport } from './routes/dashboard/driver/trips'
import { Route as DashboardDriverMessagesRouteImport } from './routes/dashboard/driver/messages'
import { Route as DashboardDriverMarketplaceRouteImport } from './routes/dashboard/driver/marketplace'
import { Route as DashboardDriverBidsRouteImport } from './routes/dashboard/driver/bids'
import { Route as DashboardAdminTripsRouteImport } from './routes/dashboard/admin/trips'
import { Route as DashboardAdminTouristsRouteImport } from './routes/dashboard/admin/tourists'
import { Route as DashboardAdminFeedbackRouteImport } from './routes/dashboard/admin/feedback'
import { Route as DashboardAdminDriversRouteImport } from './routes/dashboard/admin/drivers'
import { Route as DashboardAdminDisputesRouteImport } from './routes/dashboard/admin/disputes'
import { Route as DashboardAdminBidsRouteImport } from './routes/dashboard/admin/bids'
import { Route as AuthTouristRegisterRouteImport } from './routes/auth/tourist/register'
import { Route as AuthTouristLoginRouteImport } from './routes/auth/tourist/login'
import { Route as AuthDriverRegisterRouteImport } from './routes/auth/driver/register'
import { Route as AuthDriverLoginRouteImport } from './routes/auth/driver/login'
import { Route as AuthAdminRegisterRouteImport } from './routes/auth/admin/register'
import { Route as AuthAdminLoginRouteImport } from './routes/auth/admin/login'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTouristRoute = DashboardTouristRouteImport.update({
  id: '/tourist',
  path: '/tourist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDriverRoute = DashboardDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const Auth_layoutRoute = Auth_layoutRouteImport.update({
  id: '/auth/__layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTouristIndexRoute = DashboardTouristIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTouristRoute,
} as any)
const DashboardDriverIndexRoute = DashboardDriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDriverRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardTouristTripsRoute = DashboardTouristTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => DashboardTouristRoute,
} as any)
const DashboardTouristReceiptsRoute =
  DashboardTouristReceiptsRouteImport.update({
    id: '/receipts',
    path: '/receipts',
    getParentRoute: () => DashboardTouristRoute,
  } as any)
const DashboardTouristMessagesRoute =
  DashboardTouristMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => DashboardTouristRoute,
  } as any)
const DashboardTouristItinerariesRoute =
  DashboardTouristItinerariesRouteImport.update({
    id: '/itineraries',
    path: '/itineraries',
    getParentRoute: () => DashboardTouristRoute,
  } as any)
const DashboardTouristBidsRoute = DashboardTouristBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => DashboardTouristRoute,
} as any)
const DashboardDriverVerificationRoute =
  DashboardDriverVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => DashboardDriverRoute,
  } as any)
const DashboardDriverVehicleRoute = DashboardDriverVehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => DashboardDriverRoute,
} as any)
const DashboardDriverTripsRoute = DashboardDriverTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => DashboardDriverRoute,
} as any)
const DashboardDriverMessagesRoute = DashboardDriverMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardDriverRoute,
} as any)
const DashboardDriverMarketplaceRoute =
  DashboardDriverMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => DashboardDriverRoute,
  } as any)
const DashboardDriverBidsRoute = DashboardDriverBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => DashboardDriverRoute,
} as any)
const DashboardAdminTripsRoute = DashboardAdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminTouristsRoute = DashboardAdminTouristsRouteImport.update({
  id: '/tourists',
  path: '/tourists',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminFeedbackRoute = DashboardAdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminDriversRoute = DashboardAdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminDisputesRoute = DashboardAdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminBidsRoute = DashboardAdminBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const AuthTouristRegisterRoute = AuthTouristRegisterRouteImport.update({
  id: '/auth/tourist/register',
  path: '/auth/tourist/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTouristLoginRoute = AuthTouristLoginRouteImport.update({
  id: '/auth/tourist/login',
  path: '/auth/tourist/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDriverRegisterRoute = AuthDriverRegisterRouteImport.update({
  id: '/auth/driver/register',
  path: '/auth/driver/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDriverLoginRoute = AuthDriverLoginRouteImport.update({
  id: '/auth/driver/login',
  path: '/auth/driver/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRegisterRoute = AuthAdminRegisterRouteImport.update({
  id: '/auth/admin/register',
  path: '/auth/admin/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminLoginRoute = AuthAdminLoginRouteImport.update({
  id: '/auth/admin/login',
  path: '/auth/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth': typeof Auth_layoutRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/driver': typeof DashboardDriverRouteWithChildren
  '/dashboard/tourist': typeof DashboardTouristRouteWithChildren
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/admin/register': typeof AuthAdminRegisterRoute
  '/auth/driver/login': typeof AuthDriverLoginRoute
  '/auth/driver/register': typeof AuthDriverRegisterRoute
  '/auth/tourist/login': typeof AuthTouristLoginRoute
  '/auth/tourist/register': typeof AuthTouristRegisterRoute
  '/dashboard/admin/bids': typeof DashboardAdminBidsRoute
  '/dashboard/admin/disputes': typeof DashboardAdminDisputesRoute
  '/dashboard/admin/drivers': typeof DashboardAdminDriversRoute
  '/dashboard/admin/feedback': typeof DashboardAdminFeedbackRoute
  '/dashboard/admin/tourists': typeof DashboardAdminTouristsRoute
  '/dashboard/admin/trips': typeof DashboardAdminTripsRoute
  '/dashboard/driver/bids': typeof DashboardDriverBidsRoute
  '/dashboard/driver/marketplace': typeof DashboardDriverMarketplaceRoute
  '/dashboard/driver/messages': typeof DashboardDriverMessagesRoute
  '/dashboard/driver/trips': typeof DashboardDriverTripsRoute
  '/dashboard/driver/vehicle': typeof DashboardDriverVehicleRoute
  '/dashboard/driver/verification': typeof DashboardDriverVerificationRoute
  '/dashboard/tourist/bids': typeof DashboardTouristBidsRoute
  '/dashboard/tourist/itineraries': typeof DashboardTouristItinerariesRoute
  '/dashboard/tourist/messages': typeof DashboardTouristMessagesRoute
  '/dashboard/tourist/receipts': typeof DashboardTouristReceiptsRoute
  '/dashboard/tourist/trips': typeof DashboardTouristTripsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/driver/': typeof DashboardDriverIndexRoute
  '/dashboard/tourist/': typeof DashboardTouristIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth': typeof Auth_layoutRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/admin/register': typeof AuthAdminRegisterRoute
  '/auth/driver/login': typeof AuthDriverLoginRoute
  '/auth/driver/register': typeof AuthDriverRegisterRoute
  '/auth/tourist/login': typeof AuthTouristLoginRoute
  '/auth/tourist/register': typeof AuthTouristRegisterRoute
  '/dashboard/admin/bids': typeof DashboardAdminBidsRoute
  '/dashboard/admin/disputes': typeof DashboardAdminDisputesRoute
  '/dashboard/admin/drivers': typeof DashboardAdminDriversRoute
  '/dashboard/admin/feedback': typeof DashboardAdminFeedbackRoute
  '/dashboard/admin/tourists': typeof DashboardAdminTouristsRoute
  '/dashboard/admin/trips': typeof DashboardAdminTripsRoute
  '/dashboard/driver/bids': typeof DashboardDriverBidsRoute
  '/dashboard/driver/marketplace': typeof DashboardDriverMarketplaceRoute
  '/dashboard/driver/messages': typeof DashboardDriverMessagesRoute
  '/dashboard/driver/trips': typeof DashboardDriverTripsRoute
  '/dashboard/driver/vehicle': typeof DashboardDriverVehicleRoute
  '/dashboard/driver/verification': typeof DashboardDriverVerificationRoute
  '/dashboard/tourist/bids': typeof DashboardTouristBidsRoute
  '/dashboard/tourist/itineraries': typeof DashboardTouristItinerariesRoute
  '/dashboard/tourist/messages': typeof DashboardTouristMessagesRoute
  '/dashboard/tourist/receipts': typeof DashboardTouristReceiptsRoute
  '/dashboard/tourist/trips': typeof DashboardTouristTripsRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/driver': typeof DashboardDriverIndexRoute
  '/dashboard/tourist': typeof DashboardTouristIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/__layout': typeof Auth_layoutRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/driver': typeof DashboardDriverRouteWithChildren
  '/dashboard/tourist': typeof DashboardTouristRouteWithChildren
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/admin/register': typeof AuthAdminRegisterRoute
  '/auth/driver/login': typeof AuthDriverLoginRoute
  '/auth/driver/register': typeof AuthDriverRegisterRoute
  '/auth/tourist/login': typeof AuthTouristLoginRoute
  '/auth/tourist/register': typeof AuthTouristRegisterRoute
  '/dashboard/admin/bids': typeof DashboardAdminBidsRoute
  '/dashboard/admin/disputes': typeof DashboardAdminDisputesRoute
  '/dashboard/admin/drivers': typeof DashboardAdminDriversRoute
  '/dashboard/admin/feedback': typeof DashboardAdminFeedbackRoute
  '/dashboard/admin/tourists': typeof DashboardAdminTouristsRoute
  '/dashboard/admin/trips': typeof DashboardAdminTripsRoute
  '/dashboard/driver/bids': typeof DashboardDriverBidsRoute
  '/dashboard/driver/marketplace': typeof DashboardDriverMarketplaceRoute
  '/dashboard/driver/messages': typeof DashboardDriverMessagesRoute
  '/dashboard/driver/trips': typeof DashboardDriverTripsRoute
  '/dashboard/driver/vehicle': typeof DashboardDriverVehicleRoute
  '/dashboard/driver/verification': typeof DashboardDriverVerificationRoute
  '/dashboard/tourist/bids': typeof DashboardTouristBidsRoute
  '/dashboard/tourist/itineraries': typeof DashboardTouristItinerariesRoute
  '/dashboard/tourist/messages': typeof DashboardTouristMessagesRoute
  '/dashboard/tourist/receipts': typeof DashboardTouristReceiptsRoute
  '/dashboard/tourist/trips': typeof DashboardTouristTripsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/driver/': typeof DashboardDriverIndexRoute
  '/dashboard/tourist/': typeof DashboardTouristIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/auth'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/dashboard/tourist'
    | '/auth/admin/login'
    | '/auth/admin/register'
    | '/auth/driver/login'
    | '/auth/driver/register'
    | '/auth/tourist/login'
    | '/auth/tourist/register'
    | '/dashboard/admin/bids'
    | '/dashboard/admin/disputes'
    | '/dashboard/admin/drivers'
    | '/dashboard/admin/feedback'
    | '/dashboard/admin/tourists'
    | '/dashboard/admin/trips'
    | '/dashboard/driver/bids'
    | '/dashboard/driver/marketplace'
    | '/dashboard/driver/messages'
    | '/dashboard/driver/trips'
    | '/dashboard/driver/vehicle'
    | '/dashboard/driver/verification'
    | '/dashboard/tourist/bids'
    | '/dashboard/tourist/itineraries'
    | '/dashboard/tourist/messages'
    | '/dashboard/tourist/receipts'
    | '/dashboard/tourist/trips'
    | '/dashboard/admin/'
    | '/dashboard/driver/'
    | '/dashboard/tourist/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/auth'
    | '/auth/admin/login'
    | '/auth/admin/register'
    | '/auth/driver/login'
    | '/auth/driver/register'
    | '/auth/tourist/login'
    | '/auth/tourist/register'
    | '/dashboard/admin/bids'
    | '/dashboard/admin/disputes'
    | '/dashboard/admin/drivers'
    | '/dashboard/admin/feedback'
    | '/dashboard/admin/tourists'
    | '/dashboard/admin/trips'
    | '/dashboard/driver/bids'
    | '/dashboard/driver/marketplace'
    | '/dashboard/driver/messages'
    | '/dashboard/driver/trips'
    | '/dashboard/driver/vehicle'
    | '/dashboard/driver/verification'
    | '/dashboard/tourist/bids'
    | '/dashboard/tourist/itineraries'
    | '/dashboard/tourist/messages'
    | '/dashboard/tourist/receipts'
    | '/dashboard/tourist/trips'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/dashboard/tourist'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/auth/__layout'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/dashboard/tourist'
    | '/auth/admin/login'
    | '/auth/admin/register'
    | '/auth/driver/login'
    | '/auth/driver/register'
    | '/auth/tourist/login'
    | '/auth/tourist/register'
    | '/dashboard/admin/bids'
    | '/dashboard/admin/disputes'
    | '/dashboard/admin/drivers'
    | '/dashboard/admin/feedback'
    | '/dashboard/admin/tourists'
    | '/dashboard/admin/trips'
    | '/dashboard/driver/bids'
    | '/dashboard/driver/marketplace'
    | '/dashboard/driver/messages'
    | '/dashboard/driver/trips'
    | '/dashboard/driver/vehicle'
    | '/dashboard/driver/verification'
    | '/dashboard/tourist/bids'
    | '/dashboard/tourist/itineraries'
    | '/dashboard/tourist/messages'
    | '/dashboard/tourist/receipts'
    | '/dashboard/tourist/trips'
    | '/dashboard/admin/'
    | '/dashboard/driver/'
    | '/dashboard/tourist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  Auth_layoutRoute: typeof Auth_layoutRoute
  AuthAdminLoginRoute: typeof AuthAdminLoginRoute
  AuthAdminRegisterRoute: typeof AuthAdminRegisterRoute
  AuthDriverLoginRoute: typeof AuthDriverLoginRoute
  AuthDriverRegisterRoute: typeof AuthDriverRegisterRoute
  AuthTouristLoginRoute: typeof AuthTouristLoginRoute
  AuthTouristRegisterRoute: typeof AuthTouristRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tourist': {
      id: '/dashboard/tourist'
      path: '/tourist'
      fullPath: '/dashboard/tourist'
      preLoaderRoute: typeof DashboardTouristRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/driver': {
      id: '/dashboard/driver'
      path: '/driver'
      fullPath: '/dashboard/driver'
      preLoaderRoute: typeof DashboardDriverRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/__layout': {
      id: '/auth/__layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof Auth_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tourist/': {
      id: '/dashboard/tourist/'
      path: '/'
      fullPath: '/dashboard/tourist/'
      preLoaderRoute: typeof DashboardTouristIndexRouteImport
      parentRoute: typeof DashboardTouristRoute
    }
    '/dashboard/driver/': {
      id: '/dashboard/driver/'
      path: '/'
      fullPath: '/dashboard/driver/'
      preLoaderRoute: typeof DashboardDriverIndexRouteImport
      parentRoute: typeof DashboardDriverRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/tourist/trips': {
      id: '/dashboard/tourist/trips'
      path: '/trips'
      fullPath: '/dashboard/tourist/trips'
      preLoaderRoute: typeof DashboardTouristTripsRouteImport
      parentRoute: typeof DashboardTouristRoute
    }
    '/dashboard/tourist/receipts': {
      id: '/dashboard/tourist/receipts'
      path: '/receipts'
      fullPath: '/dashboard/tourist/receipts'
      preLoaderRoute: typeof DashboardTouristReceiptsRouteImport
      parentRoute: typeof DashboardTouristRoute
    }
    '/dashboard/tourist/messages': {
      id: '/dashboard/tourist/messages'
      path: '/messages'
      fullPath: '/dashboard/tourist/messages'
      preLoaderRoute: typeof DashboardTouristMessagesRouteImport
      parentRoute: typeof DashboardTouristRoute
    }
    '/dashboard/tourist/itineraries': {
      id: '/dashboard/tourist/itineraries'
      path: '/itineraries'
      fullPath: '/dashboard/tourist/itineraries'
      preLoaderRoute: typeof DashboardTouristItinerariesRouteImport
      parentRoute: typeof DashboardTouristRoute
    }
    '/dashboard/tourist/bids': {
      id: '/dashboard/tourist/bids'
      path: '/bids'
      fullPath: '/dashboard/tourist/bids'
      preLoaderRoute: typeof DashboardTouristBidsRouteImport
      parentRoute: typeof DashboardTouristRoute
    }
    '/dashboard/driver/verification': {
      id: '/dashboard/driver/verification'
      path: '/verification'
      fullPath: '/dashboard/driver/verification'
      preLoaderRoute: typeof DashboardDriverVerificationRouteImport
      parentRoute: typeof DashboardDriverRoute
    }
    '/dashboard/driver/vehicle': {
      id: '/dashboard/driver/vehicle'
      path: '/vehicle'
      fullPath: '/dashboard/driver/vehicle'
      preLoaderRoute: typeof DashboardDriverVehicleRouteImport
      parentRoute: typeof DashboardDriverRoute
    }
    '/dashboard/driver/trips': {
      id: '/dashboard/driver/trips'
      path: '/trips'
      fullPath: '/dashboard/driver/trips'
      preLoaderRoute: typeof DashboardDriverTripsRouteImport
      parentRoute: typeof DashboardDriverRoute
    }
    '/dashboard/driver/messages': {
      id: '/dashboard/driver/messages'
      path: '/messages'
      fullPath: '/dashboard/driver/messages'
      preLoaderRoute: typeof DashboardDriverMessagesRouteImport
      parentRoute: typeof DashboardDriverRoute
    }
    '/dashboard/driver/marketplace': {
      id: '/dashboard/driver/marketplace'
      path: '/marketplace'
      fullPath: '/dashboard/driver/marketplace'
      preLoaderRoute: typeof DashboardDriverMarketplaceRouteImport
      parentRoute: typeof DashboardDriverRoute
    }
    '/dashboard/driver/bids': {
      id: '/dashboard/driver/bids'
      path: '/bids'
      fullPath: '/dashboard/driver/bids'
      preLoaderRoute: typeof DashboardDriverBidsRouteImport
      parentRoute: typeof DashboardDriverRoute
    }
    '/dashboard/admin/trips': {
      id: '/dashboard/admin/trips'
      path: '/trips'
      fullPath: '/dashboard/admin/trips'
      preLoaderRoute: typeof DashboardAdminTripsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/tourists': {
      id: '/dashboard/admin/tourists'
      path: '/tourists'
      fullPath: '/dashboard/admin/tourists'
      preLoaderRoute: typeof DashboardAdminTouristsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/feedback': {
      id: '/dashboard/admin/feedback'
      path: '/feedback'
      fullPath: '/dashboard/admin/feedback'
      preLoaderRoute: typeof DashboardAdminFeedbackRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/drivers': {
      id: '/dashboard/admin/drivers'
      path: '/drivers'
      fullPath: '/dashboard/admin/drivers'
      preLoaderRoute: typeof DashboardAdminDriversRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/disputes': {
      id: '/dashboard/admin/disputes'
      path: '/disputes'
      fullPath: '/dashboard/admin/disputes'
      preLoaderRoute: typeof DashboardAdminDisputesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/bids': {
      id: '/dashboard/admin/bids'
      path: '/bids'
      fullPath: '/dashboard/admin/bids'
      preLoaderRoute: typeof DashboardAdminBidsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/auth/tourist/register': {
      id: '/auth/tourist/register'
      path: '/auth/tourist/register'
      fullPath: '/auth/tourist/register'
      preLoaderRoute: typeof AuthTouristRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/tourist/login': {
      id: '/auth/tourist/login'
      path: '/auth/tourist/login'
      fullPath: '/auth/tourist/login'
      preLoaderRoute: typeof AuthTouristLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/driver/register': {
      id: '/auth/driver/register'
      path: '/auth/driver/register'
      fullPath: '/auth/driver/register'
      preLoaderRoute: typeof AuthDriverRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/driver/login': {
      id: '/auth/driver/login'
      path: '/auth/driver/login'
      fullPath: '/auth/driver/login'
      preLoaderRoute: typeof AuthDriverLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin/register': {
      id: '/auth/admin/register'
      path: '/auth/admin/register'
      fullPath: '/auth/admin/register'
      preLoaderRoute: typeof AuthAdminRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin/login': {
      id: '/auth/admin/login'
      path: '/auth/admin/login'
      fullPath: '/auth/admin/login'
      preLoaderRoute: typeof AuthAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminBidsRoute: typeof DashboardAdminBidsRoute
  DashboardAdminDisputesRoute: typeof DashboardAdminDisputesRoute
  DashboardAdminDriversRoute: typeof DashboardAdminDriversRoute
  DashboardAdminFeedbackRoute: typeof DashboardAdminFeedbackRoute
  DashboardAdminTouristsRoute: typeof DashboardAdminTouristsRoute
  DashboardAdminTripsRoute: typeof DashboardAdminTripsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminBidsRoute: DashboardAdminBidsRoute,
  DashboardAdminDisputesRoute: DashboardAdminDisputesRoute,
  DashboardAdminDriversRoute: DashboardAdminDriversRoute,
  DashboardAdminFeedbackRoute: DashboardAdminFeedbackRoute,
  DashboardAdminTouristsRoute: DashboardAdminTouristsRoute,
  DashboardAdminTripsRoute: DashboardAdminTripsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardDriverRouteChildren {
  DashboardDriverBidsRoute: typeof DashboardDriverBidsRoute
  DashboardDriverMarketplaceRoute: typeof DashboardDriverMarketplaceRoute
  DashboardDriverMessagesRoute: typeof DashboardDriverMessagesRoute
  DashboardDriverTripsRoute: typeof DashboardDriverTripsRoute
  DashboardDriverVehicleRoute: typeof DashboardDriverVehicleRoute
  DashboardDriverVerificationRoute: typeof DashboardDriverVerificationRoute
  DashboardDriverIndexRoute: typeof DashboardDriverIndexRoute
}

const DashboardDriverRouteChildren: DashboardDriverRouteChildren = {
  DashboardDriverBidsRoute: DashboardDriverBidsRoute,
  DashboardDriverMarketplaceRoute: DashboardDriverMarketplaceRoute,
  DashboardDriverMessagesRoute: DashboardDriverMessagesRoute,
  DashboardDriverTripsRoute: DashboardDriverTripsRoute,
  DashboardDriverVehicleRoute: DashboardDriverVehicleRoute,
  DashboardDriverVerificationRoute: DashboardDriverVerificationRoute,
  DashboardDriverIndexRoute: DashboardDriverIndexRoute,
}

const DashboardDriverRouteWithChildren = DashboardDriverRoute._addFileChildren(
  DashboardDriverRouteChildren,
)

interface DashboardTouristRouteChildren {
  DashboardTouristBidsRoute: typeof DashboardTouristBidsRoute
  DashboardTouristItinerariesRoute: typeof DashboardTouristItinerariesRoute
  DashboardTouristMessagesRoute: typeof DashboardTouristMessagesRoute
  DashboardTouristReceiptsRoute: typeof DashboardTouristReceiptsRoute
  DashboardTouristTripsRoute: typeof DashboardTouristTripsRoute
  DashboardTouristIndexRoute: typeof DashboardTouristIndexRoute
}

const DashboardTouristRouteChildren: DashboardTouristRouteChildren = {
  DashboardTouristBidsRoute: DashboardTouristBidsRoute,
  DashboardTouristItinerariesRoute: DashboardTouristItinerariesRoute,
  DashboardTouristMessagesRoute: DashboardTouristMessagesRoute,
  DashboardTouristReceiptsRoute: DashboardTouristReceiptsRoute,
  DashboardTouristTripsRoute: DashboardTouristTripsRoute,
  DashboardTouristIndexRoute: DashboardTouristIndexRoute,
}

const DashboardTouristRouteWithChildren =
  DashboardTouristRoute._addFileChildren(DashboardTouristRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardDriverRoute: typeof DashboardDriverRouteWithChildren
  DashboardTouristRoute: typeof DashboardTouristRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardDriverRoute: DashboardDriverRouteWithChildren,
  DashboardTouristRoute: DashboardTouristRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  Auth_layoutRoute: Auth_layoutRoute,
  AuthAdminLoginRoute: AuthAdminLoginRoute,
  AuthAdminRegisterRoute: AuthAdminRegisterRoute,
  AuthDriverLoginRoute: AuthDriverLoginRoute,
  AuthDriverRegisterRoute: AuthDriverRegisterRoute,
  AuthTouristLoginRoute: AuthTouristLoginRoute,
  AuthTouristRegisterRoute: AuthTouristRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
